### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by myszon** [federomero/pretty-json#15]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/myszon/.atom/packages/pretty-json/index.coffee:35:9)
```

**Comment by federomero** [comment]
Thanks for the heads up, I removed the call to atom.workspaceView here: https://github.com/federomero/pretty-json/commit/5b1353fbbf8cc4ee09bf0a505045d3e3bcf4ff3e
