### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kriswill** [federomero/pretty-json#17]
I see a bunch of PRs and issues here that have gone unresolved.  Is the owner (@federomero) of this repo still using Atom, or you moved on?

**Comment by federomero** [comment]
I guess it depends on what you call dead :) I'm not working on adding new functionalities (though I'm open to merging them if they make sense) and I'm attending to some bug requests and deprecation warnings.

Some of these piled up in the last weeks because I was on vacation.

**Comment by kriswill** [comment]
all good! =)
