### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jrsquared** [federomero/pretty-json#19]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/jreynolds/.atom/packages/pretty-json/index.coffee:32:9)
```

**Comment by federomero** [comment]
Are you sure you are running an up-to-date version of atom and this package?

**Comment by jrsquared** [comment]
I am now.  I had to uninstall/reinstall the package and it got 0.3.2.  Thank you!

**Comment by federomero** [comment]
No problem, thanks for checking.
