### ISSUE TITLE
Does not work with non-string keys

### ISSUE THREAD

**Issue by nrmitchi** [federomero/pretty-json#2]
Currently it seems that all keys need to be quoted in order for this to function.

It seems to me that `{ a: 1, b:2, c:3 }` should be able to be formatted.

**Comment by darkdragon-001** [comment]
Any updates on this?

**Comment by lexicalunit** [comment]
I added this as a separate command "JSONify JavsScript Object Literal and Prettify" in commit 727adc9. I think it makes it clear what it is doing, so as to avoid confusing when using selected text in a ruby file, for example. Expect a new release very soon.
