### ISSUE TITLE
How to assgin keymap binding to Prettify Command?

### ISSUE THREAD

**Issue by srissel** [federomero/pretty-json#26]
Hi there,

could you please help how to add a keymap binding to Atom's keymap.cson?

Thanks in advance,
Sascha.

**Comment by ryan86** [comment]
Hi,

Have you tried the following:

1.) From the Atom menu -> 'Open Your Keymap'
2.) Enter the following at the end of your keymap file:
 
'.editor':
    'cmd-ctrl-j': 'pretty-json:prettify'

Hope this helps,
Ryan

**Comment by lexicalunit** [comment]
@srissel if what @ryan86 doesn't help, please check out http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/ for more details :)
