### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by i0sdev** [federomero/pretty-json#29]
downloaded and installed in Atom.

In a new json file, selected the whole flat codes, and hit Package > Pretty JSON > Prettify, but nothing changed...

What's the right method?

**Comment by pjnovas** [comment]
Same here, it works if the file is saved with .json extension, I couldn't make it work with a just blank sheet (not saved file)

**Comment by pjnovas** [comment]
@i0sdev Just find out a way, select all the text and hit Ctrl+Shift+P then type "pretty" and choose `Pretty Json: Prettify` and it works

**Comment by i0sdev** [comment]
tried cmd+shift+p, a list popped out and hit any of `Pretty Json`, but not work, nothing changed :(

mac yosemite, atom

**Comment by stephansarver** [comment]
This plugin does not work on OSX EL Capitan following the provided instructions.

**Comment by lexicalunit** [comment]
Doesn't work on OS X 10.11 in my experience either.

**Comment by andela-eashikodi** [comment]
The README is Officially the worst documentation i have come across. finally figuring it out and it doesn't even work
