### ISSUE TITLE
Prettifier reformats scientific notation numbers

### ISSUE THREAD

**Issue by yozlet** [federomero/pretty-json#31]
Before:

```json
{
  "float": 1.23456E4
}
```

After:

```json
{
  "float": 12345.6
}
```

I assume this is related to #3?

**Comment by lexicalunit** [comment]
`1.23456E4` is equivalent to `12345.6` so I don't see the issue here. Regardless, I've added a spec test to ensure that formatting does not destroy scientific notation equivalency in commit 64e82d3. Expect a new release very soon.
