### ISSUE TITLE
Integration with Travis-CI

### ISSUE THREAD

**Issue by lexicalunit** [federomero/pretty-json#34]
@federomero Could you please set up Travis-CI integration with this repository? It should be as simple as going to https://travis-ci.org/federomero and logging in with your github credentials, then checking off this repository on the list. I've already added a `.travis.yml` file which should take care of the rest. I can't do this myself because I am not the owner of this repository.

**Comment by federomero** [comment]
@lexicalunit It's done, it should run on your next push. Let me know if it doesn't or if you need anything else from me.

Btw, great work on the rest of the issues you took care of yesterday :)

**Comment by lexicalunit** [comment]
:+1: Thanks! I had a lot of free time due to having the flu :)
