### ISSUE TITLE
Installed this plugin but cannot figure how to execute

### ISSUE THREAD

**Issue by djangofan** [federomero/pretty-json#52]
Installed this plugin but cannot figure how to execute.  I read your document: it says select the text and then 'execute' prettify.   On a Mac, I selected all the text in a JSON file and when I right-click on it, there is no option to execute.   Your video you provide in the document doesn't say how you got that pop-down menu to appear.  Thanks.

**Comment by djangofan** [comment]
Ok, I figured it out.  I had to select the text, then pull down the Packages Menu, then choose 'Pretty JSON', then click on Prettify.   Thanks.   BTW, you should update your doc to say that.

**Comment by lexicalunit** [comment]
Thanks for the input @djangofan, I've been meaning to re-write the readme document for a while now. I'll keep this in mind when I get around to it. 👍
