### ISSUE TITLE
Prettify on save

### ISSUE THREAD

**Issue by rwwagner90** [federomero/pretty-json#53]
It would be nice if we could format JSON automatically on save, rather than having to use the command palette every time

**Comment by lexicalunit** [comment]
@rwwagner90 great idea, I just added this feature in version 1.5.0, cheers!

**Comment by rwwagner90** [comment]
Awesome, thanks!

**Comment by rwwagner90** [comment]
@lexicalunit I just updated to 1.5.0 and it seems formatting on save is set by default, and there is no way to change it. Could we add a checkbox to the settings to disable it? I know sometimes I will be making quick edits to files that adhere to someone else's formatting, and not being able to disable the option may be annoying to some users.

**Comment by lexicalunit** [comment]
There should be a setting in `pretty-json` to control this in version 1.5.0. I named it "Prettify On Save JSON":

<img width="367" alt="screen shot 2016-08-02 at 10 47 22 am" src="https://cloud.githubusercontent.com/assets/1903876/17335149/91691098-589e-11e6-98eb-11296895f71d.png">

**Comment by rwwagner90** [comment]
Ah, yeah. It did show up for me now. Not sure why it didn't initially. Sorry about that!
