### ISSUE TITLE
Feature Request: Do not stringify numbers when using "Sort and Prettify"

### ISSUE THREAD

**Issue by danmackinlay** [federomero/pretty-json#62]
This
`{"foo": -0.6579373322603248 }`
is converted to this
```
{
  "foo": "-0.6579373322603248"
}
```
when I sort and prettify.

This is bad, since I now have strings instead of numbers, and my json validator throws an exception.

**Comment by lexicalunit** [comment]
Sorry for the delay in response. I only just now saw this message in my email (plus a lot of other github messages, maybe there was some outage?).

**Comment by lexicalunit** [comment]
So this is due to the fix for #49. This only happens when using "Sort and Prettify" because of the use of `json-stable-stringify`.

**Comment by lexicalunit** [comment]
See also: #46.
