### ISSUE TITLE
Prettify truncates zeros after float value

### ISSUE THREAD

**Issue by qiaojianjack** [federomero/pretty-json#66]
When I do prettify on
`{ "float": 1.0 }`

It becomes
```
{
    "float": 1
}
```
which should have been
```
{
    "float": 1.0
}
```
This is troublesome when I try to pretty format a lot of the data modeling language dumps (such as Apache Avro records), because the .0 there matters for the encoders in that language to recognize the value as not integer.

**Comment by lexicalunit** [comment]
This is a duplicate of #46, see the discussion there for more details. Sadly the is no solution for this issue.
