### ISSUE TITLE
Add keyboard shortcuts for prettifying and minifying json

### ISSUE THREAD

**Issue by moijes12** [federomero/pretty-json#68]
Currently, there are no keyboard shortcuts to prettify and minify json. It is a inconvenient for me to to click on Package->Pretty Json->Prettify all the time.

**Comment by lexicalunit** [comment]
Closing as duplicate of #63. Please see my comment there, @moijes12, for details on how to add a keyboard shortcut for any command you use frequently. It may come in handy to know for more than just this package! 🎉
