### ISSUE TITLE
prettify on save doesn't respect preference

### ISSUE THREAD

**Issue by jonathankoren** [federomero/pretty-json#77]
Expected behavior: File is not prettified.

Actual behavior: File is prettified

Steps to reproduce: 
1) Check "Prettify On Save JSON" from the pretty-json settings pane.
2) Uncheck "Prettify On Save JSON" from the pretty-json settings pane.
3) Open a json that file that is not prettified.
4) Edit the file.
5) Save the file. Observe that it is now prettified on both the screen and the disk.

Reproducable: 100%

**Comment by lexicalunit** [comment]
Did you find a fix @jonathankoren?

**Comment by jonathankoren** [comment]
I completely misdiagnosed it. It turned out it, that Nuclide was overriding the preferences, because language-json was installed.

Next time
