### ISSUE TITLE
pretty-json attempts to format .conf files and fails

### ISSUE THREAD

**Issue by mhyousefi** [federomero/pretty-json#79]
It is a bit annoying that `pretty-json` tries to format `.conf` files, and since they are clearly not `json` files, it fails to do so and subsequently shows a large error message. So every time, I try to save stuff in `.conf` files, I have to see the error. 

Please fix it.

**Comment by lexicalunit** [comment]
@mhyousefi give v2.0.2 a try, thanks for the issue report!
